name = "Hugowind"
license = "MIT"
licenselink = "https://github.com/ianrodrigues/hugowind/blob/master/LICENSE"
description = "A minimalist theme for Hugo using Tailwind CSS."
homepage = "https://github.com/ianrodrigues/hugowind"
tags = ["minimalist", "reading", "blog", "tailwindcss"]
features = ["blog"]
min_version = "0.54.0"

[author]
  name = "Ian Rodrigues"
  homepage = "https://ianrodrigues.dev"
