name = "Tailwind Simple Blog"
license = "MIT"
licenselink = "https://github.com/ianrodrigues/tailwind-simple-blog/blob/master/license.md"
description = "A minimalist theme for Hugo using Tailwind CSS."
homepage = "https://github.com/ianrodrigues/hugo-tailwind-journal"
tags = ["minimalist", "reading", "blog", "tailwindcss"]
features = ["blog"]
min_version = "0.54.0"

[author]
  name = "Ian Rodrigues"
  homepage = "https://ianrodrigues.dev"
